# Generated by Django 2.0.3 on 2020-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pizza_pizzatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
